# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FImezdhERNBKA7xzmS7eHOLoqfiUMRVg
"""

api_key='16e3fa6809dc606fa5e160ea82e475d1'

import requests
import csv
import datetime

# Replace with your actual API key
API_KEY = "16e3fa6809dc606fa5e160ea82e475d1"
LAT = "31.5497"  # Lahore latitude
LON = "74.3436"  # Lahore longitude

# URLs for Weather + AQI
weather_url = f"https://api.openweathermap.org/data/2.5/weather?lat={LAT}&lon={LON}&appid={API_KEY}&units=metric"
pollution_url = f"http://api.openweathermap.org/data/2.5/air_pollution?lat={LAT}&lon={LON}&appid={API_KEY}"

# Get current timestamp
now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Send requests
weather_data = requests.get(weather_url).json()
pollution_data = requests.get(pollution_url).json()

# Extract fields
output = {
    "timestamp": now,
    "temperature": weather_data["main"]["temp"],
    "humidity": weather_data["main"]["humidity"],
    "wind_speed": weather_data["wind"]["speed"],
    "weather_main": weather_data["weather"][0]["main"],
    "aqi": pollution_data["list"][0]["main"]["aqi"],
    "pm2_5": pollution_data["list"][0]["components"]["pm2_5"],
    "pm10": pollution_data["list"][0]["components"]["pm10"],
    "co": pollution_data["list"][0]["components"]["co"],
    "no2": pollution_data["list"][0]["components"]["no2"]
}

# Save to CSV
file_name = "aqi_data.csv"
header = list(output.keys())

try:
    with open(file_name, mode='a', newline='') as file:
        writer = csv.DictWriter(file, fieldnames=header)
        # Write header only if file is empty
        if file.tell() == 0:
            writer.writeheader()
        writer.writerow(output)
    print("Data saved successfully.")
except Exception as e:
    print("Error saving data:", e)