name: Insert AQI data to Hopsworks

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
      HOPSWORKS_HOST: ${{ secrets.HOPSWORKS_HOST }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install hopsworks==4.2.4 pandas requests

    - name: Run ingest script
      run: python feature_store.py
