name: Train AQI Model

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:     # Manual trigger

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas numpy scikit-learn joblib

    - name: Run preprocessing script
      run: python preprocess.py

    - name: Run training script
      run: python train_model.py

    - name: Commit updated model
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add aqi_model.pkl
        git commit -m "🔄 Auto-updated model via CI/CD"
        git push
